# Define minimum Snakemake Version
from snakemake.utils import min_version
min_version("6.12.1")

# Include Config file
configfile: "config/config.yaml"

# Include report functionality
report: "../report/workflow.rst"

# This file includes common functions used in the pipeline
include: "rules/misc_snake.smk"

## Include the preprocessing rules
include: "rules/gex_cellranger.smk"
include: "rules/adt_cellranger.smk"
include: "rules/adt_hashing.smk"

## Include the scampi module
#module scampi:
#    snakefile: "/cluster/work/nexus/internal_projects/scGATE_publication/git/scAmpi_single_cell_RNA/snake/snake_scAmpi_basic_master.snake"
#    config: "config/config.yaml"

#use rule create_hdf5 from scampi as scampi_create_hdf5


# This rule defines which files should be created
localrules:
    scPreprocessing_gex_adt,


rule scPreprocessing_gex_adt:
    input:
        inputFiles=getInputFiles,
    output:
        "results/complete_sc_preprocessing_gex_adt.txt",
    params:
        samplemapFile=config["inputOutput"]["sample_map"],
        rootdir="results/",
    conda:
        "envs/scPreprocessing_gex_adt.yaml"
    resources:
        mem_mb=1000,
        time=1
    benchmark:
        "results/complete_sc_preprocessing_gex_adt.txt.benchmark"
    shell:
        "Rscript workflow/scripts/link_preprocessing_and_singlecell_pipeline.R --sampleMap {params.samplemapFile} --rootdir {params.rootdir} && date > {output} "
