import os, glob, sys, datetime

# Include Config file
configfile: "config/config.yaml"

# Include report functionality
report: "../report/workflow.rst"


# This function adapts the config object to include full path information
include: "rules/misc_snake.smk"


# input files and folders
TMPDIR = config["inputOutput"]["analysis_temp_dir"]
SAMPLEMAPPING = config["inputOutput"]["sample_map"]

# Check if the uses specified the proper input and output directories
if not "TMPDIR" in globals():
    print(
        "You have to specify the root directory where temporary files will be stored!"
    )
    sys.exit(1)


## Include the rules
include: "rules/gex_cellranger.smk"
include: "rules/adt_cellranger.smk"
include: "rules/adt_hashing.smk"


## Include Scampi as Module
# https://github.com/ETH-NEXUS/scAmpi_single_cell_RNA
# module scampi_sc:
#    snakefile:
#        "../../../../git/scAmpi_single_cell_RNA/snake/snake_scAmpi_basic_master.snake"
#    config:
#        config["scampi"]


# use rule * from scampi_sc as scampi_*


# This rule defines which files should be created
localrules:
    scPreprocessing_gex_adt,


rule scPreprocessing_gex_adt:
    input:
        inputFiles=getInputFiles,
    output:
        "results/complete_sc_preprocessing_gex_adt.txt",
    params:
        filter_cellranger=config["tools"]["link_filter_cellranger"]["call"],
        samplemapFile=config["inputOutput"]["sample_map"],
        rootdir="results/",
    resources:
        mem_mb=1000,
        time=1
    benchmark:
        "results/complete_sc_preprocessing_gex_adt.txt.benchmark"
    shell:
        "{params.filter_cellranger} --sampleMap {params.samplemapFile} --rootdir {params.rootdir} --technology ADT,GEX && date > {output}"
