inputOutput:
  input_fastqs_gex: >-
    /cluster/work/nexus/internal_projects/scGATE_publication/tests/linda_dev/fastqs_GEX/
  input_fastqs_adt: >-
    /cluster/work/nexus/internal_projects/scGATE_publication/tests/linda_dev/fastqs_ADT/
  analysis_root_dir: >-
    /cluster/work/nexus/internal_projects/scGATE_publication/tests/linda_dev/scGATE_workflow/results/
  analysis_temp_dir: >-
    /cluster/work/nexus/internal_projects/scGATE_publication/tests/linda_dev/scGATE_workflow/tmp/
  sample_map: >-
    /cluster/work/nexus/internal_projects/scGATE_publication/tests/linda_dev/scGATE_workflow/config/samplemap
resources:
  reference_transcriptome: >-
    /cluster/work/nexus/utilities/databases/singlecell/10xGenomics/gene_expression_3_0_2/refdata-cellranger-GRCh38-3.0.0
tools:
  generate_library_adt:
    mem: 200
    time: 200
    threads: 1
  cellranger_count_gex:
    call: /cluster/work/nexus/utilities/sharedPrograms/cellranger/cellranger-6.1.1/bin/cellranger
    local_cores: 24
    mem: 6000
    time: 1440
    threads: 24
    variousParams: '--chemistry SC5P-R2'
  cellranger_count_adt:
    call: >-
      /cluster/work/nexus/utilities/sharedPrograms/cellranger/cellranger-6.1.1/bin/cellranger
    local_cores: 24
    mem: 6000
    time: 1440
    threads: 24
    variousParams: '--chemistry SC5P-R2'
  create_tag_file:
    mem: 400
    time: 200
    threads: 1
  run_citeseq_count:
    call: '/cluster/customapps/nexus/single-cell/CITE-seq-Count_1.4.5/bin/CITE-seq-Count'
    variousParams: '-cbf 1 -cbl 16 -umif 17 -umil 26 --start-trim 10 '
    mem: 8000
    time: 320
    threads: 12
  create_symlink:
    mem: 200
    time: 200
    threads: 1
  analyse_hashing:
    call: Rscript workflow/scripts/analyseHashing.R
    quantileThreshold: '0.99'
    normalisation: '1,2'
    normalisation_downstream: '1'
    save_negatives: 'TRUE'
    mem: 20000
    time: 320
    threads: 8
  link_filter_cellranger:
    call: Rscript /path/to/scripts/link_preprocessing_and_singlecell_pipeline.R
